script: "bundle exec rake cucumber"

rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ree-1.8.7

gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile

branches:
  only:
    - master
